#!/usr/bin/env python3
"""Build a PNG logo/icon system from one source mark image.

Input should be a raster mark generated by an image model or supplied by the
user. The script removes a plain background, normalizes the mark, recolors it,
and exports a small brand asset system.
"""

from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Iterable

from PIL import Image, ImageDraw, ImageFilter, ImageFont, ImageOps, ImageStat


DEFAULT_COLORS = {
    "ink": "#171B18",
    "black": "#0F1110",
    "primary": "#2F6F64",
    "primary_dark": "#24574F",
    "primary_soft": "#D9E8E3",
    "paper": "#F7F8F6",
    "paper_deep": "#EEF4F2",
    "accent": "#B7791F",
    "white": "#FFFFFF",
}


def hex_rgba(value: str, alpha: int = 255) -> tuple[int, int, int, int]:
    value = value.strip().lstrip("#")
    if len(value) == 3:
        value = "".join(ch * 2 for ch in value)
    if len(value) != 6:
        raise ValueError(f"Expected 6-digit hex color, got {value!r}")
    return tuple(int(value[i : i + 2], 16) for i in (0, 2, 4)) + (alpha,)


def rgb_distance(a: tuple[int, int, int], b: tuple[int, int, int]) -> float:
    return math.sqrt(sum((x - y) ** 2 for x, y in zip(a, b)))


def estimate_background(rgb: Image.Image) -> tuple[int, int, int]:
    w, h = rgb.size
    sample = max(8, min(w, h) // 16)
    crops = [
        rgb.crop((0, 0, sample, sample)),
        rgb.crop((w - sample, 0, w, sample)),
        rgb.crop((0, h - sample, sample, h)),
        rgb.crop((w - sample, h - sample, w, h)),
    ]
    pixels: list[tuple[int, int, int]] = []
    for crop in crops:
        pixels.extend(crop.resize((8, 8), Image.Resampling.BILINEAR).getdata())
    return tuple(round(sum(px[i] for px in pixels) / len(pixels)) for i in range(3))


def make_alpha_mask(image: Image.Image, threshold: int, alpha_floor: int) -> Image.Image:
    rgba = ImageOps.exif_transpose(image).convert("RGBA")
    rgb = rgba.convert("RGB")
    original_alpha = rgba.getchannel("A")
    bg = estimate_background(rgb)
    w, h = rgba.size
    mask = Image.new("L", (w, h), 0)
    rgb_pixels = rgb.load()
    alpha_pixels = original_alpha.load()
    out = mask.load()

    for y in range(h):
        for x in range(w):
            alpha = alpha_pixels[x, y]
            r, g, b = rgb_pixels[x, y]
            distance = rgb_distance((r, g, b), bg)
            if alpha < alpha_floor:
                value = 0
            elif alpha < 245:
                value = alpha
            else:
                value = max(0, min(255, int((distance - threshold) * 5.2)))
            out[x, y] = value

    mask = mask.filter(ImageFilter.MedianFilter(3)).filter(ImageFilter.GaussianBlur(0.7))
    return mask.point(lambda px: 255 if px > 30 else px)


def normalize_mask(mask: Image.Image, canvas_size: int, mark_scale: float) -> Image.Image:
    bbox = mask.point(lambda px: 255 if px > 12 else 0).getbbox()
    if not bbox:
        raise ValueError("No visible mark detected. Use a higher-contrast source PNG or lower --threshold.")
    cropped = mask.crop(bbox)
    target = round(canvas_size * mark_scale)
    cropped.thumbnail((target, target), Image.Resampling.LANCZOS)
    canvas = Image.new("L", (canvas_size, canvas_size), 0)
    canvas.paste(cropped, ((canvas_size - cropped.width) // 2, (canvas_size - cropped.height) // 2))
    return canvas


def colorize_mask(mask: Image.Image, color: str, size: int | None = None) -> Image.Image:
    if size and mask.size != (size, size):
        mask = mask.resize((size, size), Image.Resampling.LANCZOS)
    im = Image.new("RGBA", mask.size, hex_rgba(color))
    im.putalpha(mask)
    return im


def fit_center(image: Image.Image, size: int) -> Image.Image:
    out = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    im = image.copy()
    im.thumbnail((size, size), Image.Resampling.LANCZOS)
    out.alpha_composite(im, ((size - im.width) // 2, (size - im.height) // 2))
    return out


def save_mark(mask: Image.Image, out_dir: Path, name: str, color: str) -> None:
    colorize_mask(mask, color).save(out_dir / name)


def make_app_icon(mask: Image.Image, out_dir: Path, name: str, bg: str, fg: str, rounded: bool = False) -> None:
    size = 1024
    icon = Image.new("RGBA", (size, size), hex_rgba(bg))
    if rounded:
        bg_layer = Image.new("RGBA", (size, size), (0, 0, 0, 0))
        d = ImageDraw.Draw(bg_layer)
        d.rounded_rectangle((0, 0, size, size), radius=220, fill=hex_rgba(bg))
        icon = bg_layer
    mark = colorize_mask(mask, fg, size=760)
    icon.alpha_composite(mark, ((size - 760) // 2, (size - 760) // 2))
    icon.save(out_dir / name)


def apply_font_axes(font: ImageFont.FreeTypeFont, weight: int, opsz: int) -> None:
    try:
        font.set_variation_by_axes([float(weight), float(opsz)])
    except Exception:
        pass


def load_wordmark_font(path: Path, size: int, weight: int, opsz: int) -> ImageFont.FreeTypeFont:
    font = ImageFont.truetype(str(path), size)
    apply_font_axes(font, weight, opsz)
    return font


def load_ui_font(size: int) -> ImageFont.ImageFont:
    for path in (
        "/System/Library/Fonts/SFNS.ttf",
        "/System/Library/Fonts/Helvetica.ttc",
        "/Library/Fonts/Arial.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/usr/share/fonts/truetype/liberation2/LiberationSans-Regular.ttf",
    ):
        try:
            return ImageFont.truetype(path, size)
        except Exception:
            continue
    return ImageFont.load_default()


def text_width(draw: ImageDraw.ImageDraw, text: str, font: ImageFont.FreeTypeFont, tracking: int) -> tuple[int, int, int]:
    widths: list[int] = []
    top = 9999
    bottom = -9999
    for ch in text:
        bbox = draw.textbbox((0, 0), ch, font=font)
        widths.append(bbox[2] - bbox[0])
        top = min(top, bbox[1])
        bottom = max(bottom, bbox[3])
    return sum(widths) + tracking * max(0, len(text) - 1), top, bottom


def draw_tracked_text(
    draw: ImageDraw.ImageDraw,
    xy: tuple[int, int],
    text: str,
    font: ImageFont.FreeTypeFont,
    fill: tuple[int, int, int, int],
    tracking: int,
) -> int:
    x, y = xy
    for ch in text:
        draw.text((x, y), ch, font=font, fill=fill)
        bbox = draw.textbbox((0, 0), ch, font=font)
        x += (bbox[2] - bbox[0]) + tracking
    return x


def draw_wordmark(
    base: Image.Image,
    *,
    brand: str,
    x: int,
    y_center: int,
    font_path: Path,
    font_size: int,
    weight: int,
    opsz: int,
    tracking: int,
    text_color: str,
    dot_color: str,
    show_dot: bool,
) -> None:
    draw = ImageDraw.Draw(base)
    font = load_wordmark_font(font_path, font_size, weight, opsz)
    _, top, bottom = text_width(draw, brand, font, tracking)
    text_height = bottom - top
    y = round(y_center - text_height / 2 - top - 1)
    end_x = draw_tracked_text(draw, (x, y), brand, font, hex_rgba(text_color), tracking)
    if show_dot:
        radius = max(7, round(font_size * 0.078))
        dot_x = round(end_x + font_size * 0.14)
        dot_y = round(y_center + font_size * 0.12)
        draw.ellipse((dot_x, dot_y - radius, dot_x + radius * 2, dot_y + radius), fill=hex_rgba(dot_color))


def make_lockup(
    mask: Image.Image,
    out_dir: Path,
    name: str,
    *,
    brand: str,
    font_path: Path,
    bg: str | None,
    mark_color: str,
    text_color: str,
    dot_color: str,
    show_dot: bool,
    weight: int,
    opsz: int,
) -> None:
    width, height = 1280, 320
    canvas = Image.new("RGBA", (width, height), (0, 0, 0, 0) if bg is None else hex_rgba(bg))
    mark_size = 206
    mark = colorize_mask(mask, mark_color, size=mark_size)
    mark_x = 78
    canvas.alpha_composite(mark, (mark_x, (height - mark_size) // 2))
    draw_wordmark(
        canvas,
        brand=brand,
        x=mark_x + mark_size + 66,
        y_center=height // 2,
        font_path=font_path,
        font_size=138,
        weight=weight,
        opsz=opsz,
        tracking=-2,
        text_color=text_color,
        dot_color=dot_color,
        show_dot=show_dot,
    )
    canvas.save(out_dir / name)


def make_header(
    mask: Image.Image,
    out_dir: Path,
    name: str,
    *,
    brand: str,
    tagline: str,
    font_path: Path,
    bg: str,
    mark_color: str,
    text_color: str,
    dot_color: str,
    show_dot: bool,
    weight: int,
    opsz: int,
) -> None:
    width, height = 1600, 420
    canvas = Image.new("RGBA", (width, height), hex_rgba(bg))
    mark_size = 150
    mark = colorize_mask(mask, mark_color, size=mark_size)
    mark_x, mark_y = 94, 72
    canvas.alpha_composite(mark, (mark_x, mark_y))
    draw_wordmark(
        canvas,
        brand=brand,
        x=mark_x + mark_size + 54,
        y_center=mark_y + mark_size // 2,
        font_path=font_path,
        font_size=98,
        weight=weight,
        opsz=opsz,
        tracking=-1,
        text_color=text_color,
        dot_color=dot_color,
        show_dot=show_dot,
    )
    draw = ImageDraw.Draw(canvas)
    system_font = load_ui_font(36)
    draw.text((mark_x, 290), tagline, font=system_font, fill=hex_rgba(text_color, 190))
    canvas.save(out_dir / name)


def draw_text(draw: ImageDraw.ImageDraw, xy: tuple[int, int], value: str, font: ImageFont.ImageFont, color: str, alpha: int = 255) -> None:
    draw.text(xy, value, font=font, fill=hex_rgba(color, alpha))


def make_overview(mask: Image.Image, out_dir: Path, *, brand: str, font_path: Path, colors: dict[str, str], weight: int, opsz: int) -> None:
    width, height = 2400, 1600
    sheet = Image.new("RGBA", (width, height), hex_rgba(colors["paper"]))
    draw = ImageDraw.Draw(sheet)
    title_font = load_wordmark_font(font_path, 88, weight, opsz)
    body_font = load_wordmark_font(font_path, 38, 430, 18)
    small_font = load_ui_font(27)

    def rounded_rect(xy: tuple[int, int, int, int], fill: str, radius: int = 34, outline: str | None = None) -> None:
        draw.rounded_rectangle(xy, radius=radius, fill=hex_rgba(fill), outline=hex_rgba(outline) if outline else None)

    draw_text(draw, (110, 78), f"{brand} Logo System", title_font, colors["ink"])
    draw_text(draw, (114, 188), "Newsreader lockups with a raster AI mark system.", body_font, colors["ink"], 195)

    lockups = [
        ("lockup-primary-on-paper.png", "Light header", colors["paper_deep"], colors["ink"]),
        ("lockup-paper-on-ink.png", "Dark header", colors["ink"], colors["paper"]),
    ]
    for i, (file_name, label, bg, label_color) in enumerate(lockups):
        x = 110 + i * 1110
        y = 270
        rounded_rect((x, y, x + 1030, y + 310), bg, radius=36, outline=colors["primary_soft"] if i == 0 else colors["primary_dark"])
        img = Image.open(out_dir / file_name).convert("RGBA")
        img.thumbnail((910, 230), Image.Resampling.LANCZOS)
        sheet.alpha_composite(img, (x + 56, y + 40))
        draw_text(draw, (x + 38, y + 330), label, small_font, label_color, 180)

    draw_text(draw, (110, 690), "Marks", body_font, colors["ink"])
    marks = [
        ("Primary", "mark-primary-transparent.png", colors["paper_deep"]),
        ("Ink mono", "mark-ink-transparent.png", colors["paper_deep"]),
        ("Reverse", "mark-white-transparent.png", colors["ink"]),
        ("Soft", "mark-primary-soft-transparent.png", colors["primary_dark"]),
        ("Accent", "mark-accent-transparent.png", colors["paper_deep"]),
    ]
    for i, (label, file_name, bg) in enumerate(marks):
        x = 110 + i * 430
        y = 755
        rounded_rect((x, y, x + 330, y + 330), bg, radius=46, outline=colors["primary_soft"] if bg != colors["ink"] else colors["primary_dark"])
        mark = Image.open(out_dir / file_name).convert("RGBA")
        mark.thumbnail((190, 190), Image.Resampling.LANCZOS)
        sheet.alpha_composite(fit_center(mark, 190), (x + 70, y + 54))
        draw_text(draw, (x, y + 360), label, small_font, colors["ink"], 185)

    draw_text(draw, (110, 1210), "App icons", body_font, colors["ink"])
    icons = [
        ("Paper / primary", "app-icon-paper-primary-square-1024.png"),
        ("Primary / paper", "app-icon-primary-paper-square-1024.png"),
        ("Ink / paper", "app-icon-ink-paper-square-1024.png"),
        ("Soft / dark", "app-icon-soft-dark-square-1024.png"),
    ]
    for i, (label, file_name) in enumerate(icons):
        x = 110 + i * 285
        y = 1270
        icon = Image.open(out_dir / file_name).convert("RGBA")
        icon.thumbnail((185, 185), Image.Resampling.LANCZOS)
        sheet.alpha_composite(icon, (x, y))
        draw_text(draw, (x, y + 212), label, small_font, colors["ink"], 185)

    px, py = 1320, 1210
    draw_text(draw, (px, py), "Theme colors", body_font, colors["ink"])
    palette = [
        ("Ink", colors["ink"]),
        ("Primary", colors["primary"]),
        ("Dark", colors["primary_dark"]),
        ("Soft", colors["primary_soft"]),
        ("Paper", colors["paper"]),
        ("Accent", colors["accent"]),
    ]
    for j, (name, value) in enumerate(palette):
        x = px + (j % 3) * 320
        y = py + 64 + (j // 3) * 126
        rounded_rect((x, y, x + 86, y + 86), value, radius=18, outline=colors["primary_soft"])
        draw_text(draw, (x + 108, y + 2), name, small_font, colors["ink"], 190)
        draw_text(draw, (x + 108, y + 42), value, small_font, colors["ink"], 145)

    sheet.save(out_dir / "logo-system-overview.png")


def make_favicons(out_dir: Path, base_icon: Path) -> None:
    icon = Image.open(base_icon).convert("RGBA")
    for size in (16, 32, 48, 64, 128, 180, 192, 512):
        resized = icon.resize((size, size), Image.Resampling.LANCZOS)
        resized.save(out_dir / f"favicon-{size}.png")


def write_docs(out_dir: Path, args: argparse.Namespace, colors: dict[str, str]) -> None:
    manifest = {
        "brand": args.brand,
        "source_mark": str(Path(args.mark).expanduser()),
        "output_dir": str(out_dir),
        "font": {
            "family": "Newsreader",
            "file": str(args.font),
            "license": "OFL-1.1",
            "axes": {"wght": args.font_weight, "opsz": args.font_opsz},
        },
        "colors": colors,
        "primary_assets": [
            "mark-primary-transparent.png",
            "mark-ink-transparent.png",
            "mark-white-transparent.png",
            "app-icon-paper-primary-square-1024.png",
            "app-icon-primary-paper-square-1024.png",
            "lockup-primary-on-paper.png",
            "lockup-paper-on-ink.png",
            "logo-system-overview.png",
        ],
    }
    (out_dir / "manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    readme = f"""# {args.brand} Logo System

Generated from `{args.mark}`.

Recommended assets:

- Primary transparent mark: `mark-primary-transparent.png`
- Dark/mono transparent mark: `mark-ink-transparent.png`
- Reverse transparent mark: `mark-white-transparent.png`
- Light app icon: `app-icon-paper-primary-square-1024.png`
- Primary app icon: `app-icon-primary-paper-square-1024.png`
- Header lockup on light: `lockup-primary-on-paper.png`
- Header lockup on dark: `lockup-paper-on-ink.png`
- Overview sheet: `logo-system-overview.png`

Typography:

- Wordmark: Newsreader Variable Roman
- Render settings: `wght={args.font_weight}`, `opsz={args.font_opsz}`
- Font license: OFL-1.1

Theme colors:

- Ink: `{colors["ink"]}`
- Primary: `{colors["primary"]}`
- Dark primary: `{colors["primary_dark"]}`
- Soft primary: `{colors["primary_soft"]}`
- Paper: `{colors["paper"]}`
- Accent: `{colors["accent"]}`
"""
    (out_dir / "README.md").write_text(readme, encoding="utf-8")


def build(args: argparse.Namespace) -> None:
    out_dir = Path(args.out).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)
    colors = {
        "ink": args.ink,
        "black": args.black,
        "primary": args.primary,
        "primary_dark": args.primary_dark,
        "primary_soft": args.primary_soft,
        "paper": args.paper,
        "paper_deep": args.paper_deep,
        "accent": args.accent,
        "white": args.white,
    }
    source = Image.open(Path(args.mark).expanduser())
    raw_mask = make_alpha_mask(source, args.threshold, args.alpha_floor)
    mask = normalize_mask(raw_mask, canvas_size=1024, mark_scale=args.mark_scale)
    mask.save(out_dir / "source-mark-mask.png")

    save_mark(mask, out_dir, "mark-primary-transparent.png", colors["primary"])
    save_mark(mask, out_dir, "mark-primary-dark-transparent.png", colors["primary_dark"])
    save_mark(mask, out_dir, "mark-primary-soft-transparent.png", colors["primary_soft"])
    save_mark(mask, out_dir, "mark-ink-transparent.png", colors["ink"])
    save_mark(mask, out_dir, "mark-white-transparent.png", colors["white"])
    save_mark(mask, out_dir, "mark-accent-transparent.png", colors["accent"])

    make_app_icon(mask, out_dir, "app-icon-paper-primary-square-1024.png", colors["paper"], colors["primary"])
    make_app_icon(mask, out_dir, "app-icon-primary-paper-square-1024.png", colors["primary"], colors["paper"])
    make_app_icon(mask, out_dir, "app-icon-ink-paper-square-1024.png", colors["ink"], colors["paper"])
    make_app_icon(mask, out_dir, "app-icon-soft-dark-square-1024.png", colors["primary_soft"], colors["primary_dark"])
    make_app_icon(mask, out_dir, "app-icon-paper-primary-rounded-1024.png", colors["paper"], colors["primary"], rounded=True)

    font_path = Path(args.font).expanduser().resolve()
    show_dot = not args.no_dot
    make_lockup(
        mask,
        out_dir,
        "lockup-primary-on-paper.png",
        brand=args.brand,
        font_path=font_path,
        bg=colors["paper"],
        mark_color=colors["primary"],
        text_color=colors["ink"],
        dot_color=colors["primary"],
        show_dot=show_dot,
        weight=args.font_weight,
        opsz=args.font_opsz,
    )
    make_lockup(
        mask,
        out_dir,
        "lockup-paper-on-ink.png",
        brand=args.brand,
        font_path=font_path,
        bg=colors["ink"],
        mark_color=colors["white"],
        text_color=colors["paper"],
        dot_color=colors["primary_soft"],
        show_dot=show_dot,
        weight=args.font_weight,
        opsz=args.font_opsz,
    )
    make_lockup(
        mask,
        out_dir,
        "lockup-primary-ink-transparent.png",
        brand=args.brand,
        font_path=font_path,
        bg=None,
        mark_color=colors["primary"],
        text_color=colors["ink"],
        dot_color=colors["primary"],
        show_dot=show_dot,
        weight=args.font_weight,
        opsz=args.font_opsz,
    )
    make_lockup(
        mask,
        out_dir,
        "lockup-white-transparent.png",
        brand=args.brand,
        font_path=font_path,
        bg=None,
        mark_color=colors["white"],
        text_color=colors["white"],
        dot_color=colors["primary_soft"],
        show_dot=show_dot,
        weight=args.font_weight,
        opsz=args.font_opsz,
    )

    make_header(
        mask,
        out_dir,
        "scenario-header-light.png",
        brand=args.brand,
        tagline=args.tagline,
        font_path=font_path,
        bg=colors["paper"],
        mark_color=colors["primary"],
        text_color=colors["ink"],
        dot_color=colors["primary"],
        show_dot=show_dot,
        weight=args.font_weight,
        opsz=args.font_opsz,
    )
    make_header(
        mask,
        out_dir,
        "scenario-header-dark.png",
        brand=args.brand,
        tagline=args.tagline,
        font_path=font_path,
        bg=colors["ink"],
        mark_color=colors["white"],
        text_color=colors["paper"],
        dot_color=colors["primary_soft"],
        show_dot=show_dot,
        weight=args.font_weight,
        opsz=args.font_opsz,
    )

    make_favicons(out_dir, out_dir / "app-icon-paper-primary-square-1024.png")
    make_overview(mask, out_dir, brand=args.brand, font_path=font_path, colors=colors, weight=args.font_weight, opsz=args.font_opsz)
    write_docs(out_dir, args, colors)


def parser() -> argparse.ArgumentParser:
    skill_root = Path(__file__).resolve().parents[1]
    default_font = skill_root / "assets/fonts/Newsreader[opsz,wght].ttf"
    p = argparse.ArgumentParser(description="Build a PNG logo/icon system from a source mark image.")
    p.add_argument("--mark", required=True, help="Path to source PNG mark, preferably AI-generated raster art.")
    p.add_argument("--brand", required=True, help="Brand/product name for lockups.")
    p.add_argument("--out", required=True, help="Output directory.")
    p.add_argument("--tagline", default="Clear thinking, made visible.", help="Short scenario-header tagline.")
    p.add_argument("--font", default=str(default_font), help="Path to Newsreader variable TTF.")
    p.add_argument("--font-weight", type=int, default=680)
    p.add_argument("--font-opsz", type=int, default=56)
    p.add_argument("--no-dot", action="store_true", help="Do not draw the small dot after the wordmark.")
    p.add_argument("--mark-scale", type=float, default=0.78, help="Normalized mark size within a square canvas.")
    p.add_argument("--threshold", type=int, default=28, help="Background-removal threshold.")
    p.add_argument("--alpha-floor", type=int, default=8, help="Ignore pixels with alpha below this value.")
    for key, value in DEFAULT_COLORS.items():
        p.add_argument(f"--{key.replace('_', '-')}", default=value)
    return p


def main() -> None:
    args = parser().parse_args()
    build(args)


if __name__ == "__main__":
    main()
