#!/usr/bin/env python3
"""Split a black-and-white logo exploration board into candidate PNGs.

The expected input is a flat 4x6 or similar grid generated by an image model.
The script crops each cell, trims white margins around the mark, recenters it on
a square white canvas, and writes numbered candidate images for selection.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont, ImageOps


def content_bbox(image: Image.Image, threshold: int) -> tuple[int, int, int, int] | None:
    gray = image.convert("L")
    mask = gray.point(lambda px: 255 if px < threshold else 0)
    return mask.getbbox()


def square_candidate(cell: Image.Image, size: int, trim_threshold: int, padding: float) -> Image.Image:
    rgb = ImageOps.exif_transpose(cell).convert("RGB")
    bbox = content_bbox(rgb, trim_threshold)
    if bbox:
        cropped = rgb.crop(bbox)
    else:
        cropped = rgb

    canvas = Image.new("RGB", (size, size), "white")
    max_side = max(1, round(size * (1 - padding * 2)))
    scale = max_side / max(1, max(cropped.size))
    resized_size = (
        max(1, round(cropped.width * scale)),
        max(1, round(cropped.height * scale)),
    )
    cropped = cropped.resize(resized_size, Image.Resampling.LANCZOS)
    canvas.paste(cropped, ((size - cropped.width) // 2, (size - cropped.height) // 2))
    return canvas


def label_font(size: int) -> ImageFont.ImageFont:
    for path in (
        "/System/Library/Fonts/SFNS.ttf",
        "/System/Library/Fonts/Helvetica.ttc",
        "/Library/Fonts/Arial.ttf",
    ):
        try:
            return ImageFont.truetype(path, size)
        except Exception:
            continue
    return ImageFont.load_default()


def make_contact_sheet(candidates: list[Path], out_path: Path, cols: int, cell_size: int) -> None:
    rows = math.ceil(len(candidates) / cols)
    gutter = max(24, cell_size // 12)
    label_h = max(34, cell_size // 9)
    width = cols * cell_size + (cols + 1) * gutter
    height = rows * (cell_size + label_h) + (rows + 1) * gutter
    sheet = Image.new("RGB", (width, height), "#F7F8F6")
    draw = ImageDraw.Draw(sheet)
    font = label_font(max(18, cell_size // 12))

    for i, path in enumerate(candidates):
        row, col = divmod(i, cols)
        x = gutter + col * (cell_size + gutter)
        y = gutter + row * (cell_size + label_h + gutter)
        img = Image.open(path).convert("RGB").resize((cell_size, cell_size), Image.Resampling.LANCZOS)
        sheet.paste(img, (x, y))
        draw.text((x, y + cell_size + 6), f"{i + 1:02d}", font=font, fill="#171B18")
    sheet.save(out_path)


def split(args: argparse.Namespace) -> None:
    board = Image.open(Path(args.board).expanduser())
    board = ImageOps.exif_transpose(board).convert("RGB")
    out_dir = Path(args.out).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    w, h = board.size
    left = round(w * args.margin_x)
    top = round(h * args.margin_y)
    right = round(w * (1 - args.margin_x))
    bottom = round(h * (1 - args.margin_y))
    usable_w = right - left
    usable_h = bottom - top
    cell_w = usable_w / args.cols
    cell_h = usable_h / args.rows

    candidates: list[Path] = []
    for row in range(args.rows):
        for col in range(args.cols):
            idx = row * args.cols + col + 1
            x0 = round(left + col * cell_w)
            y0 = round(top + row * cell_h)
            x1 = round(left + (col + 1) * cell_w)
            y1 = round(top + (row + 1) * cell_h)
            cell = board.crop((x0, y0, x1, y1))
            candidate = square_candidate(cell, args.size, args.trim_threshold, args.padding)
            path = out_dir / f"candidate-{idx:02d}.png"
            candidate.save(path)
            candidates.append(path)

    make_contact_sheet(candidates, out_dir / "exploration-contact-sheet.png", args.cols, args.preview_size)
    if args.selected:
        selected_path = out_dir / f"candidate-{args.selected:02d}.png"
        if not selected_path.exists():
            raise SystemExit(f"Selected candidate {args.selected} is out of range")
        Image.open(selected_path).save(out_dir / "selected-mark.png")

    print(f"wrote {len(candidates)} candidates to {out_dir}")
    if args.selected:
        print(f"selected mark: {out_dir / 'selected-mark.png'}")


def parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(description="Split a logo exploration board into numbered candidate PNGs.")
    p.add_argument("--board", required=True, help="Path to generated exploration board image.")
    p.add_argument("--out", required=True, help="Output directory for candidate PNGs.")
    p.add_argument("--cols", type=int, default=4)
    p.add_argument("--rows", type=int, default=6)
    p.add_argument("--size", type=int, default=1024, help="Square output size for each candidate.")
    p.add_argument("--preview-size", type=int, default=260, help="Cell size in the numbered contact sheet.")
    p.add_argument("--margin-x", type=float, default=0.02, help="Fractional horizontal board margin to ignore.")
    p.add_argument("--margin-y", type=float, default=0.02, help="Fractional vertical board margin to ignore.")
    p.add_argument("--trim-threshold", type=int, default=180, help="Pixels darker than this count as mark content.")
    p.add_argument("--padding", type=float, default=0.16, help="Padding fraction around trimmed mark.")
    p.add_argument("--selected", type=int, help="Candidate number to copy to selected-mark.png.")
    return p


def main() -> None:
    split(parser().parse_args())


if __name__ == "__main__":
    main()
